[build]
  functions = "functions"
[functions]
  directory = "functions"
[[redirects]]
  from = "/api/*"
  to = "https://celebrated-sawine-2b01a9.netlify.app/.netlify/functions/index/*"
  status = 200
  force = true # COMMENT: ensure that we always redirect
